#!/usr/bin/env sh
yabai -m config layout bsp

# Borders
yabai -m config window_border on
yabai -m config window_border_width 10
yabai -m config active_window_border_color 0xf0f00f0f
yabai -m config normal_window_border_color 0xff555555
yabai -m config insert_feedback_color 0xffd75f5f
yabai -m config window_shadow on
yabai -m config active_window_opacity 1.0
yabai -m config normal_window_opacity 8.0


# Paddings
yabai -m config bottom_padding 30
yabai -m config top_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

# Exceptions
yabai -m rule --add app="^System Preferences$" manage=off
yabai -m rule --add app="Settings$" manage=off
yabai -m rule --add app="^Calender$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="Preferences$" manage=off
yabai -m rule --add app="^Messages$" manage=off
yabai -m rule --add app="^KakaoTalk$" manage=off

