#!/usr/bin/env sh

spacebar -m config position             bottom
spacebar -m config height               20
spacebar -m config width                5
spacebar -m config radius               3
spacebar -m config placement            interior
spacebar -m config active_color         0xffF5B041
spacebar -m config normal_color         0xff555555
spacebar -m config title                on
spacebar -m config spaces               on
spacebar -m config clock                on
spacebar -m config power                on
spacebar -m config padding_left         20
spacebar -m config padding_right        20
spacebar -m config spacing_left         25
spacebar -m config spacing_right        15
spacebar -m config text_font            "FiraMono Nerd Font:Regular:13.0"
spacebar -m config icon_font            "FiraMono Nerd Font:Regular:13.0"
spacebar -m config background_color     0x5555552E
spacebar -m config foreground_color     0xffffffff
spacebar -m config space_icon_color     0xff458588
spacebar -m config power_icon_color     0xffcd950c
spacebar -m config battery_icon_color   0xffd75f5f
spacebar -m config dnd_icon_color       0xffa8a8a8
spacebar -m config clock_icon_color     0xffa8a8a8
spacebar -m config power_icon_strip      
spacebar -m config space_icon_strip     1 2 3 4 5 6 7 8 9
spacebar -m config space_icon           
spacebar -m config clock_icon           🕖
spacebar -m config dnd_icon             
spacebar -m config clock_format         "%Y-%m-%dT%H:%M"
