" Plug 'tpope/vim-eunuch'
Plug 'kyazdani42/nvim-tree.lua'
Plug 'LinArcX/telescope-env.nvim'
Plug 'kdheepak/lazygit.nvim'
Plug 'startup-nvim/startup.nvim'
Plug 'nvim-telescope/telescope-file-browser.nvim'
" Plug 'Pocco81/AutoSave.nvim'
